### ISSUE TITLE
Add a button to request for membership

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/analogist#16]
Should send a mail containing the ID/name of the requester, and possibly a link to his profile. An admin page with one-click resolving may be considered.

**Comment by nojhamster** [comment]
It would be worth checking if it's possible to request for board membership directly from the Trello API.

**Comment by nojhamster** [comment]
Unfortunately, requesting for board membership is not possible on Trello. In order to keep things simple, I'm considering the solution of storing requesters in mongodb and provide a way for the board admins to resolve the requests through AnalogIST. Board admins would receive a simple mail containing a link to AnalogIST.

The lazy solution would be to send a mail to the board admins with enough information for them to add the member manually from Trello.

**Comment by tporquet** [comment]
The lazy solution is fine with me ;-)

**Comment by nojhamster** [comment]
Currently wondering how a service like Gmail would handle mails with a sender name but no sender address, which is likely to be a spam.

Since Trello doesn't give access to the members mail, the receivers have to be configured manually...
