### ISSUE TITLE
The button "new platform" should be more visible

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/analogist#36]

**Comment by nojhamster** [comment]
Now a message is displayed when the search doesn't match any platform, with a big visible button if  the user can create a new one. Displaying it when "only a few are matching" is a bit tricky, since each group (by letter or status) is filtered separately.

![anim](https://cloud.githubusercontent.com/assets/3006025/10312981/b3fa0786-6c4d-11e5-9512-5dbaed98c52c.gif)

**Comment by kerphi** [comment]
Great.
An improvement idea: maybe pre-fill the platform name field with the search
input value.

**Comment by nojhamster** [comment]
Nice idea, I created another issue for this (#49)
