### ISSUE TITLE
"new analysis" button should be more visible

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/analogist#38]
Should probably be removed from the toolbar and added as a FAB somewhere around the list of analyses.

**Comment by kerphi** [comment]
:+1:

**Comment by nojhamster** [comment]
Changed for a simple button under the list.

![anim](https://cloud.githubusercontent.com/assets/3006025/10247059/80415762-6916-11e5-9b71-c5a51b6b71af.gif)

**Comment by kerphi** [comment]
Maybe "Nouvelle URL" is better than "Nouvelle analyse" because shorter and
speaks about what we add

**Comment by nojhamster** [comment]
Changed
