### ISSUE TITLE
ugly display during the first second

### ISSUE THREAD

**Issue by kerphi** [ezpaarse-project/analogist#39]
maybe a problem with CSS loading ?

![depotg1](https://cloud.githubusercontent.com/assets/328244/10189733/77f456a4-6768-11e5-9ab1-a96351a7bd59.jpg)

**Comment by nojhamster** [comment]
That's how the page looks like before angular compiles it. For now I will hide the interpolated expressions, but it will require some kind of boot loader.

**Comment by nojhamster** [comment]
Fixed in v1 thanks to SSR.
