### ISSUE TITLE
Travis failing due to outdated mongo

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/analogist#42]
History handling requires mongo 2.6+ in order to use **$position**, but Travis only provides mongo 2.4.

Possible solutions :
- find another way to handle the history
- install mongo manually (with a config like [this one](https://github.com/kraih/mango/blob/master/.travis.yml))
- find another CI tool

**Comment by kerphi** [comment]
or :
- install mongo with docker

**Comment by nojhamster** [comment]
Nice idea, implemented in 9ba9d50fa788daed78efb1087f44a16fe52e673c
