### ISSUE TITLE
Recognized as "member" but can't modify anything

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/analogist#45]
Sometimes the UI seems to stay hidden despite the user is recognized as a member of the board.

**Comment by tporquet** [comment]
NB : The two cases I had to deal with were Trello users that had not been added to the board yet. So it's not a bug per se. On the other hand, we should have a way to let the user know their rights are insufficient so they can contact us.

**Comment by nojhamster** [comment]
Then the problem is that those users were marked as "member" in the menu although they were not. When this is fixed, I think the label "invité" will be replaced by a button to request for membership. (ie. #16)

**Comment by nojhamster** [comment]
Forgot some parenthesis, so anyone was appearing as member...
