### ISSUE TITLE
Ability to modify the cards from AnalogIST

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/analogist#46]

**Comment by tporquet** [comment]
Does that mean being able: 
- to edit the link to the parser's source on github
- to move the trello card from one column to another
  directly on analogist, without needing to navigate to the trello board.

(my opinion is: the less we send our users on Trello, the better).

**Comment by nojhamster** [comment]
Exactly, one should be able to edit the description of a card, as well as moving it from a list to another. With this the main actions involving Trello would be covered.

**Comment by tporquet** [comment]
Nice!
