### ISSUE TITLE
dont like the save button

### ISSUE THREAD

**Issue by kerphi** [ezpaarse-project/analogist#54]
because:
- appears even when there is nothing to save
- should be located near the thing we are saving (the top bar means we want to save something globally for the whole application)

I'm a fan of "autosave" feature as google doc :sunglasses:

**Comment by tporquet** [comment]
if autosave is too complicated to be implemented, we could have an inactive (grey) / active (red) button depending if we have something to save or not. For now, it always seems we have something to save, even if we're only looking at an analysis.

**Comment by kerphi** [comment]
+1

**Comment by nojhamster** [comment]
Fixed in v1. Greyed out button + auto-save when no input for 5 sec.
