### ISSUE TITLE
visual indicator for platforms without any "URL analysis"

### ISSUE THREAD

**Issue by kerphi** [ezpaarse-project/analogist#59]
It could be great to have a visual indicator or be able to filter platforms in the list without any "URL analyses".
So that it could be possible to know which platforms still need to be migrated from the analogist wiki to ANG.

**Comment by tporquet** [comment]
+1 (i was thinking exactly the same while writing the mail you just received ;-))

**Comment by nojhamster** [comment]
Nice idea, it will be easy to implement once #60 is done.

**Comment by pseudom** [comment]
Done
