### ISSUE TITLE
Do not quit the page if a modification is not saved

### ISSUE THREAD

**Issue by kerphi** [ezpaarse-project/analogist#64]
Do not allow to quit without a small popup warning.
Thanks to this warning the user will not lost his work in error (ex: closing the windows clicking the wrong place...)

The popup could be similar to the one on dokuwiki:
![image](https://cloud.githubusercontent.com/assets/328244/11822065/facb7c98-a36c-11e5-9cb3-42298aa74347.png)

**Comment by tporquet** [comment]
+1
