### ISSUE TITLE
Add vol, issue, first_page, last_page in the suggested fileds of the "Nouvelle URL" form 

### ISSUE THREAD

**Issue by pseudom** [ezpaarse-project/analogist#70]
Take it form a fields.json file which contains "comments" and "help"  used in tooltips.
This file will replace rid.json, rtype.json and mime.json in the ezpaarse-platform repository https://github.com/ezpaarse-project/ezpaarse-platforms

**Comment by nojhamster** [comment]
https://github.com/ezpaarse-project/ezpaarse-platforms/issues/8 should be done first
