### ISSUE TITLE
Fix the behaviour of the back button when an analysis is selected

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/analogist#73]
Currently, the back button sends the user back to the platforms list, no matter if an analysis is selected or not. This behaviour is not intuitive and new users get confused easily. But we can hardly integrate the analysis in the breadcrumb since two analyses can be selected independently.

One solution would be to take the left analysis as a reference, so that the back button would only depend on the left analysis.

**Comment by tporquet** [comment]
+1 ;-)

**Comment by nojhamster** [comment]
This also pushes the need for automatic saves
