### ISSUE TITLE
Error on save if the user registered himself on the card

### ISSUE THREAD

**Issue by nojhamster** [ezpaarse-project/analogist#86]
POST on /cardid/members returns a 400 if the user registres himself as a card member dirextly from trello

**Comment by pseudom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gérer le cas d'erreur d'ajout d'un membre déjà existant depuis ANG](https://trello.com/c/mGE4bovS/140-gerer-le-cas-d-erreur-d-ajout-d-un-membre-deja-existant-depuis-ang)
