### ISSUE TITLE
Add a save button on analyses pages

### ISSUE THREAD

**Issue by pseudom** [ezpaarse-project/analogist#88]

**Comment by pseudom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter un bouton "enregistrer" en bas des pages d'analyses dans ANG](https://trello.com/c/enMVLszN/34-ajouter-un-bouton-enregistrer-en-bas-des-pages-d-analyses-dans-ang)

**Comment by nojhamster** [comment]
Fixed in v1
